# Mod 9 CS II

In [1]:
#Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
"""1.Load the kinematics dataset as measured on mobile sensors from the file “run_or_walk.csv”. 
List out the columns in the dataset."""

#Loading the dataset
data = pd.read_csv("run_or_walk.csv", header=0)
data.shape

(88588, 11)

In [3]:
data.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [4]:
#listing columns 
data.columns

Index(['date', 'time', 'username', 'wrist', 'activity', 'acceleration_x',
       'acceleration_y', 'acceleration_z', 'gyro_x', 'gyro_y', 'gyro_z'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88588 entries, 0 to 88587
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   date            88588 non-null  object 
 1   time            88588 non-null  object 
 2   username        88588 non-null  object 
 3   wrist           88588 non-null  int64  
 4   activity        88588 non-null  int64  
 5   acceleration_x  88588 non-null  float64
 6   acceleration_y  88588 non-null  float64
 7   acceleration_z  88588 non-null  float64
 8   gyro_x          88588 non-null  float64
 9   gyro_y          88588 non-null  float64
 10  gyro_z          88588 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 7.4+ MB


In [6]:
data.describe()

wrist      activity  acceleration_x  acceleration_y  \
count  88588.000000  88588.000000    88588.000000    88588.000000   
mean       0.522170      0.500801       -0.074811       -0.562585   
std        0.499511      0.500002        1.009299        0.658458   
min        0.000000      0.000000       -5.350500       -3.299000   
25%        0.000000      0.000000       -0.381800       -1.033500   
50%        1.000000      1.000000       -0.059500       -0.759100   
75%        1.000000      1.000000        0.355500       -0.241775   
max        1.000000      1.000000        5.603300        2.668000   

       acceleration_z        gyro_x        gyro_y        gyro_z  
count    88588.000000  88588.000000  88588.000000  88588.000000  
mean        -0.313956      0.004160      0.037203      0.022327  
std          0.486815      1.253423      1.198725      1.914423  
min         -3.753800     -4.430600     -7.464700     -9.480000  
25%         -0.376000     -0.920700     -0.644825     -1.345125  
50%         -0.221000      0.018700      0.039300      0.006900  
75%         -0.085900      0.888800      0.733700      1.398200  
max          1.640300      4.874200      8.498000     11.266200

In [7]:
"""2. Let the target variable ‘y’ be the activity and assign all the columns after it to ‘x’."""

#Target Variable
y = data.activity
y.head()

0    0
1    0
2    0
3    0
4    0
Name: activity, dtype: int64

In [8]:
#Feature Variable (Assigning all the columns after Activity)
X = data.iloc[:,5:11]
X.head()

acceleration_x  acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z
0          0.2650         -0.7814         -0.0076 -0.0590  0.0325 -2.9296
1          0.6722         -1.1233         -0.2344 -0.1757  0.0208  0.1269
2          0.4399         -1.4817          0.0722 -0.9105  0.1063 -2.4367
3          0.3031         -0.8125          0.0888  0.1199 -0.4099 -2.9336
4          0.4814         -0.9312          0.0359  0.0527  0.4379  2.4922

In [9]:
def naiveBayesClassifier(X, y):
    
    #Splitting the data in train-test with 30% of the data kept aside for testing.
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=30)
    print(f"Splitting the data with test-size as 30% and random state as 30")
    
    from sklearn.naive_bayes import GaussianNB
    clf_gaus = GaussianNB()
    clf_gaus =clf_gaus.fit(X_train, y_train)

    #Predicting the data
    y_pred = clf_gaus.predict(X_test)

    import sklearn.metrics as metrics
    score_Naive_bayes = metrics.accuracy_score(y_pred, y_test)
    print(f"The Accuracy score with the NB classifier is : {score_Naive_bayes}")

    #Printing the Confusion matrix for the NB classifier
    conf_nb = metrics.confusion_matrix(y_pred, y_test)
    print(f"Confusion matrix with the NB classifier is: \n{conf_nb}")
    
    #Printing the Classification report for the NB classifier
    cls_nb = metrics.classification_report(y_pred, y_test)
    print(f"Classification report with the NB classifier is: \n{cls_nb}")
    print('*'*40)

In [10]:
print("Predicting values using the Naive Bayes algo")
naiveBayesClassifier(X, y)

Predicting values using the Naive Bayes algo
Splitting the data with test-size as 30% and random state as 30
The Accuracy score with the NB classifier is : 0.957482033337096
Confusion matrix with the NB classifier is: 
[[13156  1000]
 [  130 12291]]
Classification report with the NB classifier is: 
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     14156
           1       0.92      0.99      0.96     12421

    accuracy                           0.96     26577
   macro avg       0.96      0.96      0.96     26577
weighted avg       0.96      0.96      0.96     26577

****************************************


In [11]:
"""4.Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors. 
Comment on the difference in accuracy between both the models."""

#Repeating the model with Accelaration values as predictors only.
#Feature Variable (Assigning all the  Accelaration values columns)
x_acln = data.iloc[:, 5:8]
x_acln.head()

acceleration_x  acceleration_y  acceleration_z
0          0.2650         -0.7814         -0.0076
1          0.6722         -1.1233         -0.2344
2          0.4399         -1.4817          0.0722
3          0.3031         -0.8125          0.0888
4          0.4814         -0.9312          0.0359

In [12]:
"""4.Repeat the model once using only the acceleration values as predictors and then using only the gyro values as predictors. 
Comment on the difference in accuracy between both the models."""

#Repeating the model with Gyro values as predictors only.
#Feature Variable (Assigning all the  Gyro values columns)
x_gyro = data.iloc[:, 8:11]
x_gyro.head()

gyro_x  gyro_y  gyro_z
0 -0.0590  0.0325 -2.9296
1 -0.1757  0.0208  0.1269
2 -0.9105  0.1063 -2.4367
3  0.1199 -0.4099 -2.9336
4  0.0527  0.4379  2.4922

In [13]:
print("Predicting values using the Naive Bayes algo having Accelaration values as predictors only.")
naiveBayesClassifier(x_acln, y)

Predicting values using the Naive Bayes algo having Accelaration values as predictors only.
Splitting the data with test-size as 30% and random state as 30
The Accuracy score with the NB classifier is : 0.9581969372013395
Confusion matrix with the NB classifier is: 
[[13190  1015]
 [   96 12276]]
Classification report with the NB classifier is: 
              precision    recall  f1-score   support

           0       0.99      0.93      0.96     14205
           1       0.92      0.99      0.96     12372

    accuracy                           0.96     26577
   macro avg       0.96      0.96      0.96     26577
weighted avg       0.96      0.96      0.96     26577

****************************************


In [14]:
print("Predicting values using the Naive Bayes algo having Gyro values as predictors only.")
naiveBayesClassifier(x_gyro, y)

Predicting values using the Naive Bayes algo having Gyro values as predictors only.
Splitting the data with test-size as 30% and random state as 30
The Accuracy score with the NB classifier is : 0.6466869849870188
Confusion matrix with the NB classifier is: 
[[9860 5964]
 [3426 7327]]
Classification report with the NB classifier is: 
              precision    recall  f1-score   support

           0       0.74      0.62      0.68     15824
           1       0.55      0.68      0.61     10753

    accuracy                           0.65     26577
   macro avg       0.65      0.65      0.64     26577
weighted avg       0.66      0.65      0.65     26577

****************************************


In [15]:
# Bottomline, the accuracy has decreased with gyro values as predictors. Hence, acceleration is a predominant feature.
# But both the features (Accelaration and gyro) are important to correctly estimate the target variable (activity)